// <auto-generated />
using System;
using AndreAirLinesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AndreAirLinesAPI.Migrations
{
    [DbContext(typeof(AndreAirLinesAPIContext))]
    [Migration("20220405142441_v7")]
    partial class v7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AndreAirLinesAPI.Model.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Federative_Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("AndreAirLinesAPI.Model.Aircraft", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Aircraft_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("AndreAirLinesAPI.Model.Airport", b =>
                {
                    b.Property<string>("IATA_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Airport_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IATA_Code");

                    b.HasIndex("AddressId");

                    b.ToTable("Airport");
                });

            modelBuilder.Entity("AndreAirLinesAPI.Model.BasePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DestinationIATA_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("InclusionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginIATA_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DestinationIATA_Code");

                    b.HasIndex("OriginIATA_Code");

                    b.ToTable("BasePrice");
                });

            modelBuilder.Entity("AndreAirLinesAPI.Model.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Class_Value")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("AndreAirLinesAPI.Model.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AircraftId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationIATA_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OriginIATA_Code")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("DestinationIATA_Code");

                    b.HasIndex("OriginIATA_Code");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("AndreAirLinesAPI.Model.Model.Passenger", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passenger_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cpf");

                    b.HasIndex("AddressId");

                    b.ToTable("Passenger");
                });

            modelBuilder.Entity("AndreAirLinesAPI.Model.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BasePriceId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int?>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("PassengerCpf")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("SalePercentage")
                        .HasColumnType("float");

                    b.Property<double>("TotalValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BasePriceId");

                    b.HasIndex("ClassId");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerCpf");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("AndreAirLinesAPI.Model.Airport", b =>
                {
                    b.HasOne("AndreAirLinesAPI.Model.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("AndreAirLinesAPI.Model.BasePrice", b =>
                {
                    b.HasOne("AndreAirLinesAPI.Model.Airport", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationIATA_Code");

                    b.HasOne("AndreAirLinesAPI.Model.Airport", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginIATA_Code");

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("AndreAirLinesAPI.Model.Flight", b =>
                {
                    b.HasOne("AndreAirLinesAPI.Model.Aircraft", "Aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftId");

                    b.HasOne("AndreAirLinesAPI.Model.Airport", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationIATA_Code");

                    b.HasOne("AndreAirLinesAPI.Model.Airport", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginIATA_Code");

                    b.Navigation("Aircraft");

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("AndreAirLinesAPI.Model.Model.Passenger", b =>
                {
                    b.HasOne("AndreAirLinesAPI.Model.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("AndreAirLinesAPI.Model.Ticket", b =>
                {
                    b.HasOne("AndreAirLinesAPI.Model.BasePrice", "BasePrice")
                        .WithMany()
                        .HasForeignKey("BasePriceId");

                    b.HasOne("AndreAirLinesAPI.Model.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("AndreAirLinesAPI.Model.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId");

                    b.HasOne("AndreAirLinesAPI.Model.Model.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerCpf");

                    b.Navigation("BasePrice");

                    b.Navigation("Class");

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });
#pragma warning restore 612, 618
        }
    }
}
